include: package:flutter_lints/flutter.yaml

analyzer:
  exclude:
    - "lib/l10n/**.g.dart"
linter:
  rules:
    - prefer_double_quotes
    - always_declare_return_types
    - cancel_subscriptions
    - avoid_print
    - constant_identifier_names
    - camel_case_types
